Implement embedded infinity
infiniflow/infinity pull request #1297
Opened 2024-06-05 12:35 UTC by Ma-cat

### What problem does this PR solve?
* use nanobind to bind infinity cpp and python api
* direct pip install infinity to run infinity on the local file system
 
Issue link:#1181

### Type of change
- [x] New Feature (non-breaking change which adds functionality)
- [x] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [x] Refactoring
- [x] Test cases
- [x] Python SDK impacted, Need to update PyPI

2024-06-12 10:58 UTC, yuzhichang commented
Remote and local test code can be combined into one.

2024-06-13 12:50 UTC, JinHai-CN commented on third_party/nanobind/ext/robin_map/tests/CMakeLists.txt
robin_map/tests directory can be removed

2024-06-13 12:51 UTC, JinHai-CN commented on third_party/nanobind/cmake/darwin-ld-cpython.sym
can be removed.

2024-06-13 12:51 UTC, JinHai-CN commented on third_party/nanobind/cmake/darwin-ld-pypy.sym
can be removed

2024-06-13 12:51 UTC, JinHai-CN requested changes
Do we also need to build dockerfile?

2024-06-17 12:51 UTC, merged